### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by lilith** [sherif-elmetainy/DotnetGD#1]
These might be helpful, take what you can: 

https://github.com/imazen/gd-libgd - AppVeyor builds Libgd and all dependencies

Auto-generated machine-level bindings for libgd (you'll still have to add another layer). 
https://github.com/imazen/gd-dotnet-bindings-generator

Background: https://github.com/imazen/Graphics-vNext

The hard part is getting proper test coverage and fixing the underlying bugs in libgd as you discover them.

**Comment by sherif-elmetainy** [comment]
Thanks a lot for your help.

I think thumbs.sh scripts on the [libgd](https://github.com/libgd/libgd) repository and all the related dependencies was your work. I did clone those repositories on my machine and they were very helpful and I them to build the native libgd on both Windows and Ubuntu. I am grateful for that.

The auto generated stuff looks great, I didn't see those before, specially the unit tests, I will definitely have a look at them, and use them.

I know getting good test coverage is the hardest part. My current plan is to get the wrapper done, fix bugs in my own code then start worrying about libgd bugs. I did find a few issues in libgd, for example passing a wrong font name when drawing strings causes nasty crashes, a null font name causes access violation exception, etc. Currently I am relying on validating some parameters in the wrapper, but I am sure that won't be enough when it's dont.

But I am hoping that libgd having been around for many years now and being widely used as the main graphics library for PHP and other frameworks, there won't be a lot of bugs in the native libgd itself. 

I will definitely be looking at your work, and may be I will ask you some questions in the future (if you don't mind).

Thanks again for your support.
